services:
  comfyui:
    build: ./docker_nvidia_new
    image: nvidia12_8:latest
    # command: ["sleep","infinity"]
    ports:
      # Web UI is exposed on port 8188 inside the container.
      - "8188:8188"
    networks:
      - docker-comfyui
    volumes:
      # Note: running Docker Desktop on Windows, use named volumes (WSL) and not bind mounts as this will have a huge impact on performance!
      # Persist python site-packages as no python env is being used
      - site-packages:/usr/local/lib/python3.12/site-packages
      # Persist actual comfyui app
      - comfyui_app:/comfyui
      # Persist models. Change extra_model_paths.yaml
      - comfyui_models:/comfyui_models
      # Persist in/out folder. Bind mount Windows drive to access files from Windows
      - D:\comfyui_in_out:/comfyui_in_out
    # Make sure you've installed the NVIDIA Container Toolkit and restart the Docker daemon before first use.
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
volumes:
# Existing volumes, set external:true or compose will try to recreate them 
  site-packages:
    external: true
  comfyui_app:
    external: true
  comfyui_models:
    external: true
  comfyui_in_out:
    external: true
networks:
  docker-comfyui:
    external: true