apiVersion: v1
kind: PersistentVolume
metadata:
  name: site-packages
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/docker-desktop-disk/data/docker/volumes/site-packages/_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: site-packages-pvc
spec:
  volumeName: site-packages
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-app
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/docker-desktop-disk/data/docker/volumes/comfyui_app/_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-app-pvc
spec:
  volumeName: comfyui-app
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-models
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/docker-desktop-disk/data/docker/volumes/comfyui_models/_data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-models-pvc
spec:
  volumeName: comfyui-models
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: comfyui-in-out
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/host/d/comfyui_in_out
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-in-out-pvc
spec:
  volumeName: comfyui-in-out
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""